"""add task isCompleted column

Revision ID: 60ccbdb5a893
Revises: c61ba0a46da0
Create Date: 2020-07-09 08:00:52.015192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ccbdb5a893'
down_revision = 'c61ba0a46da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('isCompleted', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'task', 'priority', ['priority_id'], ['priority_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'isCompleted')
    # ### end Alembic commands ###
