"""create priority table

Revision ID: 6d257f9a9ec9
Revises: 654811bc7466
Create Date: 2020-06-25 09:45:22.973437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d257f9a9ec9'
down_revision = '654811bc7466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('priority_id')
    )
    op.add_column('task', sa.Column('priority_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'priority', ['priority_id'], ['priority_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'priority_id')
    op.drop_table('priority')
    # ### end Alembic commands ###
