"""add task project_id column

Revision ID: f44ba1a65da8
Revises: 60ccbdb5a893
Create Date: 2020-07-09 09:20:51.009883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44ba1a65da8'
down_revision = '60ccbdb5a893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pr_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'priority', ['priority_id'], ['priority_id'])
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['project_id'])
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['user_id'])
    op.drop_column('task', 'project_id')
    op.drop_table('project')
    # ### end Alembic commands ###
